In [54]:
import numpy as np

In [55]:
arr = np.arange(1, 11)

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[0]

1

In [58]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [59]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [60]:
arr[0:3] = 100

In [61]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [62]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [63]:
arr = np.arange(0,11)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [67]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[1]

array([20, 25, 30])

In [73]:
arr_2d[1][0]

20

In [74]:
arr_2d[1,0]

20

In [75]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [76]:
arr_2d[2]

array([35, 40, 45])

In [77]:
arr_2d[2, :]

array([35, 40, 45])

In [78]:
arr_2d[2,:]

array([35, 40, 45])

In [81]:
arr2d = np.zeros((10,10))

arr_length = arr2d.shape[1]

In [82]:
arr_length

10

In [85]:
for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [87]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [88]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [90]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [92]:
bool_arr = arr>4

In [94]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [95]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
x=2

In [97]:
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr