In [11]:
import numpy as np

In [14]:
arr = np.arange(1, 11)

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr[0]

1

In [20]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [21]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [29]:
arr[0:1] = 100

In [30]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])